### ISSUE TITLE
Error for php server and remove old accout. Appreciate any help!

### ISSUE THREAD

**Issue by ds544545g** [Toni-d-e-v/Aurora-Icloud-bypass#10]
Hello
I got iphone 8, ios 13.2, locked in icloud, bypassed with checkra1

1.I get this error for Removes old icloud account conected to the device 

Aurora IOS remove old icloud account, ONLY WORKS ON JAILBROKEN IPHONES
Checking for python3...
python3 is installed
Checking for pip3...
pip3 is installed
Installing required libs...
Requirement already satisfied: paramiko in /usr/lib/python3/dist-packages (2.12.0)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
Launching shell
Aurora remove old icloud by Toni.Dev
Forwarding local port 2222 to remote port 44
Incoming connection to 2222
Waiting for devices...
Connecting to device <MuxDevice: ID 1 ProdID 0x12a8 Serial 'b'57cee6d2324cc0d1a584654b66033c06a4508125'' Location 0x1000f>
Connection established, relaying data
PLEASE RESTART YOUR PHONE
Done!
----------------------------------------
Exception occurred during processing of request from ('127.0.0.1', 34606)
Traceback (most recent call last):
  File "/usr/lib/python3.11/socketserver.py", line 691, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.11/socketserver.py", line 361, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.11/socketserver.py", line 755, in __init__
    self.handle()
  File "/home/table/Programs/androidhack/Aurora-Icloud-bypass/./source/scripts/remove_oldicloud.py", line 71, in handle
    fwd.handle()
  File "/home/table/Programs/androidhack/Aurora-Icloud-bypass/./source/scripts/remove_oldicloud.py", line 47, in handle
    s = self.b.recv(self.max_buffer - len(self.btoa))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer

2. php server error

Aurora IOS PHP UNLOCK
Checking for python3...
python3 is installed
Checking for pip3...
pip3 is installed
Installing required libs...
Requirement already satisfied: paramiko in /usr/lib/python3/dist-packages (2.12.0)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
Launching shell
Aurora  Toni.Dev
Forwarding local port 2222 to remote port 44
Incoming connection to 2222
Waiting for devices...
Connecting to device <MuxDevice: ID 1 ProdID 0x12a8 Serial 'b'57cee6d2324cc0d1a584654b66033c06a4508125'' Location 0x1001f>
Connection established, relaying data
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/paramiko/sftp_client.py", line 130, in __init__
    server_version = self._send_version()
                     ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/paramiko/sftp.py", line 134, in _send_version
    t, data = self._read_packet()
              ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/paramiko/sftp.py", line 201, in _read_packet
    x = self._read_all(4)
        ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/paramiko/sftp.py", line 188, in _read_all
    raise EOFError()
EOFError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/table/Programs/androidhack/Aurora-Icloud-bypass/./source/scripts/php.py", line 139, in <module>
    sftp = client.open_sftp()
           ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/paramiko/client.py", line 573, in open_sftp
    return self._transport.open_sftp_client()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/paramiko/transport.py", line 1142, in open_sftp_client
    return SFTPClient.from_transport(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/paramiko/sftp_client.py", line 170, in from_transport
    return cls(chan)
           ^^^^^^^^^
  File "/usr/lib/python3/dist-packages/paramiko/sftp_client.py", line 132, in __init__
    raise SSHException("EOF during negotiation")
paramiko.ssh_exception.SSHException: EOF during negotiation

Any help appreciated. A good day!

**Comment by Toni-d-e-v** [comment]
Try to check your usb cable, or the phone is not jailbreaked.
